install.packages("tidyverse", dependencies = TRUE)
install.packages("gplots", dependencies = TRUE)
install.packages("ape", dependencies = TRUE)
install.packages("BiocManager", dependencies = TRUE)
install.packages("car", dependencies = TRUE)
install.packages("data.table", dependencies = TRUE)
install.packages("DataCombine", dependencies = TRUE)
install.packages("EMMREML", dependencies = TRUE)
install.packages("foreach", dependencies = TRUE)
install.packages("doParallel", dependencies = TRUE)
install.packages("lme4", dependencies = TRUE)
install.packages("scatterplot3d", dependencies = TRUE)
install.packages("genetics", dependencies = TRUE)
install.packages("LDheatmap", dependencies = TRUE)
install.packages("gridExtra", dependencies = TRUE)
install.packages("yaml", dependencies = TRUE)
install.packages("bigmemory", dependencies = TRUE)
install.packages("biganalytics", dependencies = TRUE)
BiocManager::install("Biobase", update = FALSE, ask = FALSE)
BiocManager::install("snpStats", update = FALSE, ask = FALSE)
BiocManager::install("multtest", update = FALSE, ask = FALSE)
BiocManager::install("zlibbioc", update = FALSE, ask = FALSE)
install.packages("LDheatmap", dependencies = TRUE)
